routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;


Route::get('/', function () {
    return view('welcome');
});

Route::resource('/productos', 'ProductoController');

Route::resource('/movimientos', 'MovimientoController');

Route::resource('/movimientosDetalles', 'MovimientoDetallesController');


Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

app/Movimiento.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Movimiento extends Model
{
    protected $table = 'movimientos';
        protected $fillable = ['folio','fecha', 'comentario', 'tipo', 'status', 'usuario' ];


    public function productos(){
        
        return $this->hasMany('App\Producto', 'folio', 'folio');

    }
    }

app/Http/Controllers/MovimientoController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Producto;
use App\Movimiento;
// use App\Http\Controllers\DB;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Auth\SessionGuard;
// use Illuminate\Support\DB;
use Illuminate\Support\Facades\DB;

class MovimientoController extends Controller
{
    public function __construct(){
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $productos=Producto::all();
        $movimientos=Movimiento::all()->sortByDesc('id');;
        return view('movimientos.index')->with(compact('movimientos'));

    }
    
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {      
        //Esta parte es funcional para crear
        // $productos=Producto::all();
        // $usuario=Auth::user()->name;
        // $movimientos=Movimiento::all();
        // return view('movimientos.create')->with(compact('movimientos','productos', 'usuario'));
    
        // //Se usara para pruebas de una consulta a la base de datos

        $productos=Producto::all()->pluck('codigo');
        $usuario=Auth::user()->name;
        $movimientos=Movimiento::all()->pluck('folio');
        

        // dd($productos, $movimientos);
        
        return view('movimientos.create')->with(compact('movimientos','productos', 'usuario'));
    
}
        /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public  function generadorRandom($length = 6) 
    {
        $characters = '0123456789AEIOU';
        $charactersLength = strlen($characters);
        $randomString = '';
        for ($i = 0; $i < $length; $i++) {
            $randomString .= $characters[rand(0, $charactersLength - 1)];
        }
        return $randomString;
    }
    public function store(Request $request)
    {
        $productos=Producto::all();
        $movimientos=Movimiento::all();   
        $movimientos= request()->except('_token');
        $movimientos['folio']=$this->generadorRandom();
        
            $request->validate([
                'fecha'=>['required'],
                'comentario'=>['required'],
                'tipo'=>['required'],
                'status'=>['required'],
                'usuario'=>['required'],
            ]);

        if($movimientos['tipo']==1){
            //Ingreso de productos
            Movimiento::insert($movimientos);
            return redirect()->route('productos.create'); 
        }else{
            //salida de productos
            Movimiento::insert($movimientos);
            return redirect()->route('productos.index'); 

        }  
    }
    
    /**
     * Display the specified resource.
     *
     * @param  \App\Movimiento  $movimiento
     * @return \Illuminate\Http\Response
     */
    public function show(Movimiento $movimiento)
    {   
        // $movimientos=Movimiento::find($movimiento->id);
        
        $productos=$movimiento->productos;
        
        return view('movimientos.prueba')->with(compact('productos'));
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Movimiento  $movimiento
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $movimientos=Movimiento::all();
        $movimientos=Movimiento::findOrFail($id);
        return view('movimientos.edit')->with(compact('movimientos'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Movimiento  $movimiento
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $movimientos=Movimiento::all();
        $movimientos=Movimiento::findOrFail($id);
        $movimientos  ->fecha           =$request->get('fecha');
        $movimientos  ->comentario      =$request->get('comentario');
        $movimientos  ->tipo            =$request->get('tipo');
        $movimientos  ->status          =$request->get('status');
        $movimientos  ->usuario         =$request->get('usuario');

            $request->validate([
                'fecha'=>['required'],
                'comentario'=>['required'],
                'tipo'=>['required'],
                'status'=>['required'],
                'usuario'=>['required'],
            ]);

        $movimientos->save();
        return redirect()->route('movimientos.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Movimiento  $movimiento
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $movimientos=Movimiento::findOrFail($id);
        $movimientos->delete();
        return redirect()->route('movimientos.index');
    }
}

resources/views/movimientos/create.blade.php
@extends('layouts.app')

@section('content')

<h6>rVMqfS2aJGUth29</h6>

<div class="col">
<a class="btn btn-sussec" href="/movimientos">regresar</span></span></a>
</div>

<div>
{{ Form::open(['url'=>'/movimientos', 'method'=>'post', 'files'=>True, 'novalidate']) }}
    
    {{ Form::label('fecha','Fecha ') }}
    {{ Form::date('fecha', \Carbon\Carbon::now(), ['class'=>'form-control']) }}

    {{ Form::label('comentario','Comentarios: ') }}
    {{ Form::text('comentario', null, ['class'=>'form-control']) }}

    {{ Form::label('tipo','Tipo: ') }}
    {{ Form::select('tipo',[
        'Almacen' => ['Salida', 'Entrada']], ['class'=>'form-control']) }}
 
    {{ Form::label('status','Estado: ', ['class'=>'form-control']) }}
        <p>0=Baja 1=Activa 2=Aplicada</p>
    {{ Form::select('status',['Estado' => ['0', '1','2']], ['class'=>'form-control']) }}

    {{ Form::label('usuario','Usuario: ') }}
    {{ Form::text('usuario', $usuario, ['class'=>'form-control'] ) }}

      <button class="btn btn-success">Crear Movimiento</button>

{{ Form::close() }}

@endsection
{{-- Add modal --}}
<!-- Button trigger modal -->
    {{-- <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
        Agregar Productos
      </button>
      
      
      <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Productos</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body" >
            {{-- @include('productos.create') --}}
            {{-- {{ Form::open(['url'=>'/productos', 'method'=>'post',  'files'=>True]) }}
    
                {{ Form::label('codigo','Codigo: ') }}
                {{ Form::text('codigo', null) }}

                {{ Form::label('descripcion','Descripcion: ') }}
                {{ Form::text('descripcion', null) }}

                {{ Form::label('precio','Precio: ') }}
                {{ Form::text('precio', null) }}

                {{ Form::label('Unidad','Unidad: ') }}
                {{ Form::select('unidad',['Tipo' => ['Pza', 'Kilo','Metro']]) }}

                {{ Form::label('status','Estado: ') }}
                {{ Form::number('status', null) }}
                
                <button class="btn btn-success" >Guardar</button>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        {{-- <button type="button" class="btn btn-primary">Guardar</button> --}}
                    {{-- </div> --}}

            {{-- {{ Form::close() }} --}}
        {{-- </div> --}}
        
      {{-- </div> --}}
    {{-- </div>  --}}
  {{-- </div> --}}

resources/views/movimientos/edit.blade.php
@extends('layouts.app')

@section('content')<h1> Estas en editar</h1>
<div class="col">
    <a class="btn" href="/movimientos"> Regresar</a>
</div>

{{ Form::open(['route'=>['movimientos.update', $movimientos->id],'method'=>'put']) }}    
    
    {{-- {{ Form::label('folio','Folio') }}
    {{ Form::text('movimientos_id', $movimientos->movimientos_id) }} --}}

    {{ Form::label('fecha','Fecha ') }}
    {{ Form::date('fecha', $movimientos->fecha,['class'=>'form-control']) }}

    {{ Form::label('comentario','Comentarios: ') }}
    {{ Form::text('comentario', $movimientos->comentario, ['class'=>'form-control']) }}

    {{ Form::label('tipo','Tipo: ') }}
    {{ Form::select('tipo',[
        'Almacen' => ['Salida', 'Entrada']], $movimientos->tipo) }}

    {{ Form::label('status','Estado: ') }}
        <p>0=Baja 1=Activa 2=Aplicada</p>
    {{ Form::select('status',['Estado' => ['0', '1','2']], $movimientos->status) }}

    {{ Form::label('usuario','Usuario: ') }}
    {{ Form::text('usuario', $movimientos->usuario, ['class'=>'form-control']) }}

        <button class="btn btn-success">Guardar</button>

{{ Form::close() }}
@endsection

resources/views/movimientos/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="">
        <a class="btn btn-primary" href='/movimientos/create'>Añadir Movimiento</a>
    </div>
<div style="margin: 20px">
    <table class="table table-hover" style="width: 1100px; margin: 0 auto;">
        <thead>    
            <tr>
                <th></th>
                <th></th>
                <th>Folio</th>
                <th>Fecha</th>
                <th>Descripcion</th>
                <th>Tipo</th>
                <th>Estado</th>
                <th>Usuario</th>
            </tr>
        </thead>
        @foreach($movimientos as $movi) 
            <tbody>
                <tr>
                    <td><a href="{{ route('movimientos.edit', $movi->id )}}" class="btn btn-success">Editar</a></td>
                    <td>
                        {{ Form::open(['method'=>'DELETE', 'route'=>['movimientos.destroy', $movi->id]])}}
                            <button class="btn btn-danger">Eliminar</button>
                        {{ Form::close() }}
                    </td>
                    <td>{{ $movi->folio }}</td>
                    <td>{{ $movi->fecha }}</td>
                    <td>{{ $movi->comentario }}</td>
                    <td>{{ $movi->tipo }}</td>
                    <td>{{ $movi->status }}</td>
                    <td>{{ $movi->usuario }}</td>
                    {{-- <td><button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal{{ $movi->id }}">
                        Ver Detalles
                        </button>
                    </td>   --}}
                    <td>
                      <a href="{{  route('movimientos.show', $movi->id) }}" class="btn btn-success">Ver</a>
                    </td>
                </tr>
            </tbody>
            <div class="modal fade" id="exampleModal{{ $movi->id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog modal-lg" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">{{ $movi->fecha }}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                        {{ $movi->folio }}
                        {{ $movi->comentario }}
                        {{ $movi->tipo }}
                  </div>
                  <div class="modal-footer">
                  </div>
                </div>
              </div>
            </div>
        @endforeach                     
    </table>
</div>
@endsection

resources/views/movimientos/prueba.blade.php
@extends('layouts.app')

@section('content')
<h1>Detalles</h1>

@foreach($productos as $producto)

        <table class="table table-light">
            <tbody>
                <tr>
                    <td>{{ $producto->codigo }}</td>
                    <td>{{ $producto->descripcion }}</td>
                    <td>{{ $producto->precio }}</td>
                </tr>
            </tbody>
        </table>
@endforeach

@endsection